name: Go Test and Codecov

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Replace with your desired Go version

      - name: Run Go tests and generate coverage report
        run: |
          go test -coverprofile=coverage.txt ./...
        env:
          GOCACHE: /tmp/.cache

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Make sure you have a Codecov token set as a secret in your repository

      - name: Cleanup
        run: rm coverage.txt
